Version =20
VersionRequired =20
PublishOption =1
    RecordSelectors = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    TabularCharSet =238
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =15690
    DatasheetFontHeight =11
    ItemSuffix =50
    Right =20550
    Bottom =12285
    DatasheetGridlinesColor =14806254
        0xacf72e580a12e540
    End
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    AllowDatasheetView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            TextFontCharSet =238
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            TextFontCharSet =238
            Width =1701
            Height =283
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            BorderLineStyle =0
            Width =1701
            Height =1701
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            BorderShade =65.0
            ShowPageHeaderAndPageFooter =1
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =0
            BackColor =15849926
            Name ="NagłówekFormularza"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =2
            BackTint =20.0
        End
            CanGrow = NotDefault
            Height =6591
            Name ="Szczegóły"
            AutoHeight =1
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    OverlapFlags =85
                    OldBorderStyle =0
                    Left =60
                    Top =2265
                    Width =15630
                    Height =4305
                    TabIndex =8
                    BorderColor =10921638
                    Name ="czasyPracy"
                    SourceObject ="Form.czasyPracy"
                    GridlineColor =10921638

                    LayoutCachedLeft =60
                    LayoutCachedTop =2265
                    LayoutCachedWidth =15690
                    LayoutCachedHeight =6570
                End
                    OverlapFlags =85
                    Left =1680
                    Top =120
                    Width =2490
                    Height =390
                    ForeColor =16777215
                    Name ="Polecenie1"
                    Caption ="Przeglądaj"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =1680
                    LayoutCachedTop =120
                    LayoutCachedWidth =4170
                    LayoutCachedHeight =510
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =5282738
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =5282738
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =5282738
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =5282738
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =120
                    Top =120
                    Width =1500
                    Height =390
                    FontSize =14
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =5282738
                    Name ="Etykieta2"
                    Caption ="Zlecenia:"
                    GroupTable =1
                    GridlineColor =10921638
                    LayoutCachedLeft =120
                    LayoutCachedTop =120
                    LayoutCachedWidth =1620
                    LayoutCachedHeight =510
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =1
                End
                    OverlapFlags =85
                    Left =4230
                    Top =120
                    Width =2490
                    Height =390
                    TabIndex =1
                    ForeColor =16777215
                    Name ="Polecenie5"
                    Caption ="Dodaj nowe"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =4230
                    LayoutCachedTop =120
                    LayoutCachedWidth =6720
                    LayoutCachedHeight =510
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =5282738
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =5282738
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =5282738
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =5282738
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =1680
                    Top =1020
                    Width =2490
                    Height =390
                    TabIndex =4
                    ForeColor =16777215
                    Name ="btnPracownicy"
                    Caption ="Pracownicy"
                    OnClick ="[Event Procedure]"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =1680
                    LayoutCachedTop =1020
                    LayoutCachedWidth =4170
                    LayoutCachedHeight =1410
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =6702914
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =6702914
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =6702914
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =6702914
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =120
                    Top =1020
                    Width =1500
                    Height =390
                    FontSize =14
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =6702914
                    Name ="Etykieta13"
                    Caption ="Kadra:"
                    GroupTable =1
                    GridlineColor =10921638
                    LayoutCachedLeft =120
                    LayoutCachedTop =1020
                    LayoutCachedWidth =1620
                    LayoutCachedHeight =1410
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =1
                End
                    OverlapFlags =85
                    Left =4230
                    Top =1020
                    Width =2490
                    Height =390
                    TabIndex =5
                    ForeColor =16777215
                    Name ="btnDzialy"
                    Caption ="Działy"
                    OnClick ="[Event Procedure]"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =4230
                    LayoutCachedTop =1020
                    LayoutCachedWidth =6720
                    LayoutCachedHeight =1410
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =6702914
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =6702914
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =6702914
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =6702914
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =1680
                    Top =570
                    Width =2490
                    Height =390
                    TabIndex =2
                    ForeColor =16777215
                    Name ="btnKlienci"
                    Caption ="Przeglądaj"
                    OnClick ="[Event Procedure]"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =1680
                    LayoutCachedTop =570
                    LayoutCachedWidth =4170
                    LayoutCachedHeight =960
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =6702914
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =6702914
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =6702914
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =6702914
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =120
                    Top =570
                    Width =1500
                    Height =390
                    FontSize =14
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =6702914
                    Name ="Etykieta24"
                    Caption ="Klienci:"
                    GroupTable =1
                    GridlineColor =10921638
                    LayoutCachedLeft =120
                    LayoutCachedTop =570
                    LayoutCachedWidth =1620
                    LayoutCachedHeight =960
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =1
                End
                    OverlapFlags =85
                    Left =4230
                    Top =570
                    Width =2490
                    Height =390
                    TabIndex =3
                    ForeColor =16777215
                    Name ="btnNowyKlient"
                    Caption ="Dodaj nowego"
                    OnClick ="[Event Procedure]"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =4230
                    LayoutCachedTop =570
                    LayoutCachedWidth =6720
                    LayoutCachedHeight =960
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =6702914
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =6702914
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =6702914
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =6702914
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =1680
                    Top =1470
                    Width =2490
                    Height =390
                    TabIndex =6
                    ForeColor =16777215
                    Name ="Polecenie32"
                    Caption ="Statusy zleceń"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =1680
                    LayoutCachedTop =1470
                    LayoutCachedWidth =4170
                    LayoutCachedHeight =1860
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =6702914
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =6702914
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =6702914
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =6702914
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
                    OverlapFlags =85
                    Left =120
                    Top =1470
                    Width =1500
                    Height =390
                    FontSize =14
                    FontWeight =700
                    BorderColor =8355711
                    ForeColor =6702914
                    Name ="Etykieta33"
                    Caption ="Ustawienia:"
                    GroupTable =1
                    GridlineColor =10921638
                    LayoutCachedLeft =120
                    LayoutCachedTop =1470
                    LayoutCachedWidth =1620
                    LayoutCachedHeight =1860
                    RowStart =3
                    RowEnd =3
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =1
                End
                    OverlapFlags =85
                    Left =4230
                    Top =1470
                    Width =2490
                    Height =390
                    TabIndex =7
                    ForeColor =16777215
                    Name ="Polecenie48"
                    Caption ="Typy pracowników"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =4230
                    LayoutCachedTop =1470
                    LayoutCachedWidth =6720
                    LayoutCachedHeight =1860
                    RowStart =3
                    RowEnd =3
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =6702914
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderColor =6702914
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =6702914
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =6702914
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =1
                    WebImagePaddingBottom =1
                End
            End
        End
            Height =0
            Name ="StopkaFormularza"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
CodeBehindForm
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Private Sub btnDzialy_Click()
   DoCmd.openForm "Dzialy"
End Sub

Private Sub btnKlienci_Click()
   DoCmd.openForm "klienci"
End Sub

Private Sub btnNowyKlient_Click()
   DoCmd.openForm "szczegolyKlienta", , , , acFormAdd
End Sub

Private Sub btnPracownicy_Click()
   DoCmd.openForm "pracownicy"
End Sub
