Version =20
VersionRequired =20
PublishOption =1
    RecordSelectors = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    TabularCharSet =238
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =8998
    DatasheetFontHeight =11
    ItemSuffix =40
    Right =20550
    Bottom =12285
    DatasheetGridlinesColor =14806254
        0x18f747f7a912e540
    End
    RecordSource ="klienci"
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    AllowDatasheetView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            TextFontCharSet =238
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            BackStyle =0
            OldBorderStyle =0
            BorderLineStyle =0
            SizeMode =3
            PictureAlignment =2
            Width =1701
            Height =1701
            BorderColor =16777215
            GridlineColor =16777215
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            TextFontCharSet =238
            Width =1701
            Height =283
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            TextFontCharSet =238
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            BorderLineStyle =0
            Width =1701
            Height =1701
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            BorderShade =65.0
            ShowPageHeaderAndPageFooter =1
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =542
            Name ="NagłówekFormularza"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
                    OverlapFlags =85
                    TextAlign =1
                    Left =300
                    Top =60
                    Width =1740
                    Height =460
                    FontSize =20
                    BorderColor =8210719
                    ForeColor =6702914
                    Name ="Auto_Nagłówek0"
                    Caption ="KLIENT"
                    GroupTable =2
                    GridlineColor =10921638
                    LayoutCachedLeft =300
                    LayoutCachedTop =60
                    LayoutCachedWidth =2040
                    LayoutCachedHeight =520
                    LayoutGroup =2
                    BorderThemeColorIndex =2
                    BorderTint =100.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                    OverlapFlags =85
                    Left =2715
                    Top =60
                    Width =1815
                    Height =450
                    FontSize =10
                    ForeColor =16777215
                    Name ="btnZapisz"
                    Caption ="Zamkij i zapisz"
                    OnClick ="[Event Procedure]"
                    GroupTable =3
                    GridlineColor =10921638

                    LayoutCachedLeft =2715
                    LayoutCachedTop =60
                    LayoutCachedWidth =4530
                    LayoutCachedHeight =510
                    LayoutGroup =3
                    ForeThemeColorIndex =-1
                    Gradient =0
                    BackColor =5282738
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    OldBorderStyle =0
                    BorderColor =14136213
                    HoverColor =5282738
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =5282738
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =-1
                    PressedForeColor =4210752
                    GroupTable =3
                    WebImagePaddingLeft =2
                    WebImagePaddingTop =2
                    WebImagePaddingRight =2
                    WebImagePaddingBottom =2
                End
            End
        End
            Height =4335
            Name ="Szczegóły"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =165
                    Width =6515
                    Height =340
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="nazwaKlienta"
                    ControlSource ="nazwaKlienta"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =165
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =505
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =165
                            Width =2158
                            Height =340
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta3"
                            Caption ="Nazwa klienta"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =165
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =505
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =690
                    Width =6515
                    Height =345
                    TabIndex =1
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="pelnaNazwa"
                    ControlSource ="pelnaNazwa"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =690
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =1035
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =690
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta6"
                            Caption ="Pełna nazwa"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =690
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =1035
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =1215
                    Width =6515
                    Height =345
                    TabIndex =2
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="NIP_PESEL"
                    ControlSource ="NIP_PESEL"
                    StatusBarText ="Albo NIP albo Pesel"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =1215
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =1560
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =1215
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta9"
                            Caption ="NIP/PESEL"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =1215
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =1560
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =1740
                    Width =6515
                    Height =345
                    TabIndex =3
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="ulica"
                    ControlSource ="ulica"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =1740
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =2085
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =1740
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta12"
                            Caption ="Ulica"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =1740
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =2085
                            RowStart =3
                            RowEnd =3
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =2265
                    Width =6515
                    Height =345
                    TabIndex =4
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="nrDomu_Mieszkania"
                    ControlSource ="nrDomu_Mieszkania"
                    StatusBarText ="Zapisane po sleszu, np. 14/52"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =2265
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =2610
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =2265
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta15"
                            Caption ="Nr domu / mieszkania"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =2265
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =2610
                            RowStart =4
                            RowEnd =4
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =2790
                    Width =6515
                    Height =345
                    TabIndex =5
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="kodPocztowy"
                    ControlSource ="kodPocztowy"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =2790
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =3135
                    RowStart =5
                    RowEnd =5
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =2790
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta18"
                            Caption ="Kod pocztowy"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =2790
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =3135
                            RowStart =5
                            RowEnd =5
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =3315
                    Width =6515
                    Height =345
                    TabIndex =6
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="miasto"
                    ControlSource ="miasto"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =3315
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =3660
                    RowStart =6
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =3315
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta21"
                            Caption ="Miasto"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =3315
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =3660
                            RowStart =6
                            RowEnd =6
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2445
                    Top =3840
                    Width =6515
                    Height =345
                    TabIndex =7
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =5282738
                    ForeColor =4210752
                    Name ="uwagi"
                    ControlSource ="uwagi"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2445
                    LayoutCachedTop =3840
                    LayoutCachedWidth =8960
                    LayoutCachedHeight =4185
                    RowStart =7
                    RowEnd =7
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =225
                            Top =3840
                            Width =2158
                            Height =345
                            FontWeight =700
                            LeftMargin =44
                            TopMargin =22
                            RightMargin =44
                            BottomMargin =22
                            BorderColor =8355711
                            Name ="Etykieta24"
                            Caption ="Uwagi"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =225
                            LayoutCachedTop =3840
                            LayoutCachedWidth =2383
                            LayoutCachedHeight =4185
                            RowStart =7
                            RowEnd =7
                            LayoutGroup =1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =1
                        End
                    End
                End
            End
        End
            Height =0
            Name ="StopkaFormularza"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
CodeBehindForm
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Private Sub btnZapisz_Click()
   Call zamknijFormularz(Me.Name)
End Sub
